fixed bug where par2 stops on empty directories. Also, added documentation

diff --git a/parscrub b/parscrub
--- a/parscrub
+++ b/parscrub
@@ -7,7 +7,12 @@
 # do not crop into one's files when syncing to another machine (i.e.,
 # backup), or other glitches on storage devices. Of course, resiliancy
 # is determined by the redundancy value passed to par2 when creating
-# the pairity files.
+# the pairity files. The idea is inspired by the "scrub" feature of
+# the zfs and btrfs filesystems. Here, new pairity files are only
+# created when the script is run, not online like with those filesystems.
+# However, here, the parity files reside as hidden files in each directory,
+# so they move with the files when they are transfered from one device or
+# machine to another.
 
 # When run, all files in the current directory and all sub-directories
 # are checked for corruption by par2. Wherever par2 blockfiles are not
@@ -18,7 +23,12 @@
 # This is intended to be non-destructive to all non-par2 files. Only a
 # couple temp files and par2 files are ever written to or erased. If par2
 # encounters an error (like a file needing to be repaired), the script
-# simply exits so that 'par2repair' can be run manually.
+# simply exits so that 'par2repair' can be run manually. I also intentionally
+# left this script inflexible (without arguments). I want it to be reliable
+# in it's current form. If a different function is desired (such as changing
+# a parameter to par2), then one should make the change below and thouroughly
+# test the modified script. The script is intended to be simple and
+# readable to facilitate this type of use.
 
 # Author: Jason Locklin
 
@@ -50,27 +60,32 @@ do
     unique=$( cat .archivelist .filelist | sort | uniq -u )
     if [ "${#unique}" != "0" ]
     then
-      echo "Newfiles in current directory: $unique"
+      echo "New files in current directory: $unique"
       newfiles=true
     else
       echo "No new files in directory, moving on to next one..."
       newfiles=false
     fi
     rm .archivelist
-    rm .filelist
+    rm .filelist   #removing temporary files
 
   else
-    echo "No pairity files in current directory."
+    echo "No existing pairity files in current directory."
     emptydir=true
   fi
 
   # If files in directory not covered by existing par2 files (no par2 files OR new files).
   if $newfiles || $emptydir
   then
-    echo "Creating new pairity files..."
-    rm *.par2 # warning: potentially destructive.
-    # Create new par2 files for files in current directory.
-    par2 c -m512 -r5 -n1 .check.par2 * || exit 1
+    #Check for empty directory ('par2 c *' fails in empty directories) 
+    if [ "$(ls -A )" ]; then
+      echo "Creating new pairity files..."
+      rm *.par2 # warning: potentially destructive.
+      # Create new par2 files for files in current directory.
+      par2 c -m512 -r5 -n1 .check.par2 * || exit 1
+    else
+     echo "Directory is is Empty"
+    fi
   fi
   cd $STRT # Return to starting directory
 done
